### ISSUE TITLE
bed input is likely not handled correctly

### ISSUE THREAD

**Issue by MichaelHiller** [glarue/intronIC#4]
First, thanks a bunch for this useful tool. 

I was using it with -b input.bed (instead of gff or gtf) and when I use bed12 format, where exons are specified as blocks in field 10-12, intronIC recognizes only a single intron, which is the transcription start and transcription end of the gene. I could see this based on the bed output or when looking into the intron.iic file. 

Therefore, I tried it just with the coordinates of a single intron, provided as a bed4 (chrom, intron start, intron end, name), but then I get 
[#] [!] ERROR: No intron sequences found. Check for annotation/genome headers mismatch. Exiting now.

Could you pls explain how to use intronIC with bed as input? 
Thx a lot
Michael

**Comment by MichaelHiller** [comment]
Sorry, I made a mistake with bed4. Of course, the tool needs bed6 to also specify the strand. 

Here is my example input, which refers to an intron in ENST00000533089.5 (TGFBR3) with human hg38 coords
```chr1	91734899	91754994	intron.bed	1000	-```

This runs with intronIC; however, the acceptor splice sites that is exacted it not the correct one. 
```cat TEST/test.meta.iic ```
```intron.bed	8.8199	GT-CA	CAT|GTATCCTTGC...TTCTCCTTGACA/CCAGTTTTCATC...AAACA|GAA	TGAGGGTTCTGTGGTCCAGTTTTCATCAGCAAAC[TTCTCCTTGACA]GCAGAAACA	20095	.	.	.	u12	.```
and the bed output coords are also not correct, as they differ from the input
```cat TEST/test.bed.iic ``` 
```chr1	91734900	91754994	intron.bed;8.819%	98.8198787239447	-```

In this case, the acceptor is CAG, but intronIC uses CA as the acceptor,
and the output bed differs by 1 bp in the start (acceptor because of - strand).

**Comment by MichaelHiller** [comment]
Hi Graham, 
I did some more tests with a gencode gff as input, which works well. 
But the bed.iic output is off by 1bp at the beginning, likely because of the 0-based coords (https://en.wikipedia.org/wiki/BED_(file_format))  

Here is an example. 
![image](https://github.com/glarue/intronIC/assets/8644098/cdf494a8-56f5-4b28-ab5d-9271a489d2a2)


If I may, I would like to ask three more questions

1. Why do some introns like "ENSG00000171777.17@ENST00000587738.2-intron_3(16);[c:-1];[n]" have extra info [c:-1] etc? 
2. Some introns classified as u12 have negative scores like
```ENSG00000286891.1@ENST00000662371.1-intron_1(1);[e];[i]	-12.2209	GT-AG	CCT|GTATCATTTG...TATTTCTTAACT/TATTTCTTAACT...ATCAG|GAA	TGAGTATGGATGGGCATACTGAATAAAAATA[TATTTCTTAACT]CGTCTTTATCAG	913	ENST00000662371.1	ENSG00000286891.1	1	1	2.72	.	u12	exon``` 
Why is this? 

3. When running intronIC it seems to first train the model again. 
`[#] Training set score vectors constructed: [20690] U2, [387] U12
[#] Training SVM using reference data
Starting optimization round 1/5
Starting optimization round 2/5
Starting optimization round 3/5
Starting optimization round 4/5
Starting optimization round 5/5
[#] Range for 'C' after [5] rounds of optimization: [976.5411685881514]-[976.5419176464368]
[#] Set classifier value for 'C': [976.5415431172212]
[#] Training classifier with optimized hyperparameters
`
Is there a way to use the pre-trained model that you used in the NAR paper? 

Thx a lot for your help
Michael

**Comment by glarue** [comment]
Hi Michael,

I'll try to take these in order!

### Q0

How is the BED file you're using being generated? Your example annotation,

>`chr1	91734899	91754994	intron.bed	1000	-`

corresponds (please correct me if I'm wrong) to the following GFF3 exon annotations (the annotation file may be slightly different from what you're using but it looks like the coordinates match as expected):
```
1	havana	exon	91734776	91734898	.	-	.	Parent=transcript:ENST00000533089;Name=ENSE00002197555;constitutive=0;ensembl_end_phase=-1;ensembl_phase=-1;exon_id=ENSE00002197555;rank=8;version=1
1	havana	exon	91754995	91755062	.	-	.	Parent=transcript:ENST00000533089;Name=ENSE00002160471;constitutive=0;ensembl_end_phase=-1;ensembl_phase=-1;exon_id=ENSE00002160471;rank=7;version=1
```

The associated intron, then, has coordinates `(91734899, 91754994)`, as listed in your BED file example. However, as you also point out, BED files are 0-indexed, so in the BED file itself the "start" coordinate (actually the "end" since it's on the negative strand) needs to be decremented by 1 to `91734898` to match the BED format spec. Hopefully, most established software that generates BED output will do this automatically. That being said, embarrassingly it appears that `intronIC` does in fact have a bug where it does _not_ do the appropriate coordinate correction in its BED _output_ (although it correctly accounts for the 0-based indexing in the _input_).

**To summarize**: when supplying `intronIC` with intron coordinates in BED format, you need to ensure that the "start" (or lower, in any case) coordinate has been decremented by 1 relative to the coordinate shown in e.g. the GTF/GFF3 file. `intronIC` also needs to be updated to correctly reflect this change in its _output_ BED file.

### Q1

The extra metadata in the intron label is described [here](https://github.com/glarue/intronIC/wiki/Data-filtering-notes); in your specific example, the `[c:-1]` means the intron boundaries were auto-corrected to -1 (both start and end) because of a putative misannotation (where a strong 5'SS U12-type motif was found 1 bp upstream of an intron which is annotated as having non-canonical splice sites); `[n]` means the intron has non-canonical splice sites.

### Q2

See the [Wiki description](https://github.com/glarue/intronIC/wiki/Output-files#metaiic) of the `meta.iic` file for additional details but briefly, the classification listed in the second to last column of that file is the binary label assigned by the model without considering the probability threshold. The default threshold of 90% used by `intronIC` is conservative, and depending on application one might want to include _all_ introns classified as U12-type, not just those classified above a certain percent probability. In most cases, the vast majority of introns classified as U12-type are well above the 90% probability threshold (green in [this figure](https://raw.githubusercontent.com/glarue/intronIC/main/images/homo_sapiens.cds.example.plot.scatter.iic.png)); the introns tagged with `u12` in the `meta.iic` file would also include the red and orange introns in that figure as well.

The way `intronIC` has typically been used is to consider all introns with relative scores (the second column in `meta.iic`) greater than 0 (which corresponds to a U12-type probability of > 90%) to be U12-type; this metric is the basis for the number of U12-type introns reported in the `log.iic` output.

### Q3

During development, I initially had the classifier be trained on a per-genome basis using a variable number of putative U2-type introns. Ultimately, I abandoned that approach and by default use the training data supplied with `intronIC`, but the classifier is still trained each run. At some point I should simply supply a default model with `intronIC`, but unless you explicitly specify different training data, the resulting model should be the same as the one we used in the _NAR_ paper. I appreciate you reminding me of this; I'll put it on the to-do list. 😅

Please let me know if anything in the above remains unclear, and I will push an update to `intronIC` addressing the output BED coordinates ASAP.

**Comment by MichaelHiller** [comment]
Hi Graham, 

Thx a lot for the fast response. 

**Q0:** We have a script to generate bed6 for introns from a bed12 (and I just verified that this works correctly). 
But this case above was just a single intron test to see if intronIC works with this input format (after my bed12 test failed with using transcription start-end). It is an intron of ENST00000533089. Since I manually 'constructed' this bed6 line, I made a mistake with the start coord. Thx for noticing that. 

Maybe it could be documented that intronIC works with bed6 and not with bed12 records. 

**Q1**: Cool. I wasn't aware of the auto correct feature. I like it to point out potential problematic introns. But if we want to trust the introns we have, is there a way to switch auto correct off via a parameter? 

Q2 and Q3: Thx for the explanation. 

I'll try the updated code. 
Thx a lot
Michael

**Comment by glarue** [comment]
Hi Michael,

Regarding the BED format, I agree this should be documented better. The root of the issue you describe with your BED12 file, however, may not have as much to do with the fact that it's BED12 (as `intronIC` simply ignores any fields after the first 6) as that it is describing non-intronic features (given that you mention that it has annotated `exon` features). When using BED format for input, `intronIC` expects the BED file to describe only `intron` features; it only does interpolation between e.g. `exon` or `CDS` features when parsing a GTF/GFF file. I can certainly try to clarify this in the documentation.

The start coordinate issue in the output file should be fixed in [#99b5aaa](https://github.com/glarue/intronIC/commit/99b5aaa8f5ba967943871d337f1a6f54554fdd8f).

I added a new argument, `--no_nc_ss_adjustment` (https://github.com/glarue/intronIC/commit/d5ae113384bdcd5466e04bc5da20a9278580b282) to avoid the inference of putatively-misannotated U12-type introns—you can update to `intronIC v1.5.1` to pull in both changes. Let me know if you encounter any additional unexpected behavior!

**Comment by MichaelHiller** [comment]
Hi Graham, 

thanks a bunch for the fix. Works now very well. 

However, I was testing it on a large (all RefSeq + GenCode, ~400k unique introns) set of introns and it crashed. I then repeatedly split into chunks and ended up with this case as one intron (there are likely more) where intronIC repeatedly error exits. 

```
cat test.bed
chr1	239705715	239706321	intron27487	0	-

../intronIC.py -g hg38.fa -b test.bed -n test -p 16 -i
[#] Starting intronIC [v1.5.1] run on [test (TEst)]
[#] Run command: [/beegfs/home/mhiller/src/intronIC-main/intronIC/intronIC.py -g /beegfs/home/mhiller/src/intronIC-main/intronIC/test_data/hg38.fa -b /beegfs/home/mhiller/src/intronIC-main/intronIC/test_data/test.bed -n test -p 16 -i]
[#] [1] introns found in [test.bed]
Traceback (most recent call last):
  File "/beegfs/home/mhiller/src/intronIC-main/intronIC/test_data/../intronIC.py", line 6079, in <module>
    main()
  File "/beegfs/home/mhiller/src/intronIC-main/intronIC/test_data/../intronIC.py", line 5113, in main
    final_introns = filter_introns_write_files(
  File "/beegfs/home/mhiller/src/intronIC-main/intronIC/test_data/../intronIC.py", line 4726, in filter_introns_write_files
    for intron in get_sub_seqs(
  File "/beegfs/home/mhiller/src/intronIC-main/intronIC/test_data/../intronIC.py", line 2682, in get_sub_seqs
    if u12_nc_ss_adjustment and intron.noncanonical and u12_correction(intron):
  File "/beegfs/home/mhiller/src/intronIC-main/intronIC/test_data/../intronIC.py", line 2346, in u12_correction
    intron.phase = _shift_phase(intron.phase, shift)
  File "/beegfs/home/mhiller/src/intronIC-main/intronIC/test_data/../intronIC.py", line 2318, in _shift_phase
    index = phases.index(int(phase))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

# This is how the intron looks like. Yes a GA donor is weird, but it is otherwise proper DNA. 
twoBitToFa hg38.2bit stdout -bed=test.bed
>intron27487
GAAAGTATCCTTTCTGTCAGTAAAGTTTTCCTTCAATCCCATAAATAAAT
CATTTACAAATAATCTTCTAAATATTTAGAATGTAATAATAACATAATTA
TAAATTATATTAATAATGTATGTTTATTACATTTTATTGCATATTCACTA
TATATAATATATGTTAGTTTGTATTTATTATAATTTAGTTGTATATCATG
AATTATTTATAATTCACATATAACTATAATATATAAATATAACATAAAAT
AAATTTAATAATTTATAAAAAACAATTTAAAATAATCTAAATAAATGATA
ATCATTCTCTTTGACATCCAAGCTCCTTATCAGACTTACAACATTTAATT
CTTACTTCTCTTTTATTTTTAATCTCATCTACCTTTATCATTTGTATTAC
AACTTTGCATCTCAGTTGTATATAAAAGCTTACTTAGTATTCCAAGGTAA
TTTTATCACCTTGTACACACTGGCCATGGAGCTCCATTGCCTAGAATAAT
GTCTCTATTCTTTATGTTGAACATCAAGGCTACTTGATATATATATATAT
CGTGAATCTATCTGCCAGCCTAAACGTCATTTTCTCTTCTTTATATCCTC
ATACAG

# I also extracted just chr1 as a fasta and it crashes too
../intronIC.py -g chr1.fa -b test.bed -n test -p 16 -i
[#] Starting intronIC [v1.5.1] run on [test (TEst)]
[#] Run command: [/beegfs/home/mhiller/src/intronIC-main/intronIC/intronIC.py -g /beegfs/home/mhiller/src/intronIC-main/intronIC/test_data/chr1.fa -b /beegfs/home/mhiller/src/intronIC-main/intronIC/test_data/test.bed -n test -p 16 -i]
[#] [1] introns found in [test.bed]
Traceback (most recent call last):
  File "/beegfs/home/mhiller/src/intronIC-main/intronIC/test_data/../intronIC.py", line 6079, in <module>
    main()
  File "/beegfs/home/mhiller/src/intronIC-main/intronIC/test_data/../intronIC.py", line 5113, in main
    final_introns = filter_introns_write_files(
  File "/beegfs/home/mhiller/src/intronIC-main/intronIC/test_data/../intronIC.py", line 4726, in filter_introns_write_files
    for intron in get_sub_seqs(
  File "/beegfs/home/mhiller/src/intronIC-main/intronIC/test_data/../intronIC.py", line 2682, in get_sub_seqs
    if u12_nc_ss_adjustment and intron.noncanonical and u12_correction(intron):
  File "/beegfs/home/mhiller/src/intronIC-main/intronIC/test_data/../intronIC.py", line 2346, in u12_correction
    intron.phase = _shift_phase(intron.phase, shift)
  File "/beegfs/home/mhiller/src/intronIC-main/intronIC/test_data/../intronIC.py", line 2318, in _shift_phase
    index = phases.index(int(phase))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

# but chr1.fa is large enough. So it is not an out of bound issue
faSize chr1.fa
1390889289 bases (84231453 N's 1306657836 real 629202839 upper 677454959 lower) in 305 sequences in 1 files
Total size: mean 4560292.8 sd 23621714.8 min 7309 (chr13_ML143363v1_fix) max 248956422 (chr1) median 192462
```

Would be great if you could have a look. 
Thx

**Comment by MichaelHiller** [comment]
If I may, three more questions. 
Q1: If I used bed6 as input, it is necessary to give the -i flag if several introns have the same coords (and just a different name in the bed6 record)? 

Q2: Is the new --no_nc_ss_adjustment parameter also relevant for bed6 input? If so, where can I find out which introns may be incorrect, if I don't specify this parameter, thus allowing for shifts.

Q3: intronIC also detects introns with non-canonical splice sites. In which file is this tracked? 

Thx again
Michael

**Comment by glarue** [comment]
Hooray, more errors!

So, the first issue is a bug (due to my not having used the BED input extensively) which I believe I have a fix for that I will push shortly. The details aren't interesting but the short version is that when putatively misannotated introns are found, there is a process to create a new annotation file with exon coordinates correspondingly adjusted to match the new intron coordinates. The subroutine performing that correction wasn't properly checking the type of the input annotation file, and was trying to use a procedure designed for GTF/GFF annotations instead of BED annotations, which caused the error.

For your other questions:

1. If introns have identical coordinates, you will need to use the `-d` flag to include them in the output (the scoring is only performed on a single intron, and is propagated to any other introns with identical coordinates). Duplicates are determined based on the genomic sequence record and coordinates only; non-duplicate introns from alternate isoforms (i.e., not the longest) are what can be included using `-i`. If you do not use `-d`, however, you can still get information about introns with duplicate coordinates in the `.dupe_map.iic` file (which provides a one-to-many mapping between included introns in the first column and their annotated duplicates in the second).
2. This unfortunately isn't something I've implemented so far; as it stands, the intron coordinates are either corrected and reported or not. It would definitely be possible to add this functionality in the future (perhaps in a separate output file or something) but it would take a bit of work. Best advice for the moment (sorry that it's not more streamlined) would be to simply run twice with and without the `--no_nc_ss_adjustment` arg and write a small script to extract the names of the corrected introns (the base name of each intron should be the same for the two runs if no other options are changed).
3. Non-canonical introns are denoted with the `[n]` tag in their labels, but there is no separate file generated specifically for non-canonical introns. The most common nc termini are summarized in the `log.iic` file; if you want to get more info about all the non-canonical introns, you can use a tool like `grep` to pull the lines from the relevant file(s) with `[n]` in them. If you'd like a complete summary of the annotated splice sites in the output introns, you can do something like the following:
```
cut -f 3 <my_output.meta.iic> | sort | uniq -c | sort -k1 -n
```

**Comment by MichaelHiller** [comment]
Hi Graham, 

thanks so much for quickly fixing this. It works now and I can run intronIC on essentially all introns annotated by RefSeq_all + GenCode. I also understand all output files now. 

However, I have to report another discrepancy that I can't explain (sorry).
I was running intronIC either on the genCode gff file or after converting the gff into bed12 and splitting it into all introns. 
Although the bed.iic and meta.iic have the same number of lines, there are a few hundred more U12 introns discovered when I use bed as input. 

I ran the gff input also with unzipping the file and got the same output (exit 0).
I copied all files (input + output) to 
``wget https://genome.senckenberg.de/download/intronIC_debug/files.tar.gz``
for debugging.


```

# run on the gff3
intronIC.py -g hg38.fa -a gencode.v44.annotation.gff3.gz -n gff -p 16 --no_nc_ss_adjustment

# convert to genePred, then bed12 and then extract all introns
gff3ToGenePred gencode.v44.annotation.gff3.gz gencode.v44.gp                
genePredToBed gencode.v44.gp gencode.v44.bed
bed12ToIntrons.perl gencode.v44.bed > gencode.v44.intron.bed
# run it
time ../intronIC.py -g hg38.fa -b gencode.v44.intron.bed -n bed -p 16 --no_nc_ss_adjustment

# extract all U12 introns
grep u12 gff.meta.iic | cut -f2-5,13 | s > u12.gff
grep u12 bed.meta.iic | cut -f2-5,13 | s > u12.bed
# number differs
wc -l u12.*
  1036 u12.bed
   730 u12.gff

diff u12.bed u12.gff | h 
3d2
< -0.1333	GT-AG	CCT|GTATCCATTT...ATATCCCTAATA/ATATCCCTAATA...AAAAG|GTT	CTTTATATGATAATAAGAACTTTGTCCACAGAAG[ATATCCCTAATA]ACAAAAAAG	u12
5d3
< -0.1652	GT-AG	AGA|GTATCCTAAA...TGCTCCTTGACT/ATACTGTTTATT...GATAG|GTT	ATACTGTTTATTGGCAATTTTAAAGCTTATACAGA[TGCTCCTTGACT]TTTGATAG	u12
7,8d4
< -0.2124	GT-AG	CTT|GTATCCTCAC...ACTACCTTAAAC/TACTACCTTAAA...CTTAG|GAA	TTGTTAAGGTCTATAATGTAGCCTGTT[ACTACCTTAAAC]CTATGGACTCACTTAG	u12
< -0.312	GT-AG	GCC|GTATCCGCCG...TCCTCCTTAACC/TTTGTGTTTATC...CTCAG|CCT	TTTGTGTTTATCTTCCTCAAAGTAAGCTCT[TCCTCCTTAACC]CTTGATTTCTCAG	u12
10,13d5
< -0.6681	GT-AG	ACT|GTATCCTCAA...CTGTCCTCAACG/TCTGTCCTCAAC...TCTAG|AGT	AGAAAAGCACTTGCTGAAACACAAAGTTTTGTT[CTGTCCTCAACG]AACTGTCTAG	u12
< -0.8572	GT-AG	ACT|GTATCCTCAA...CTGTCCTCAACG/TCTGTCCTCAAC...TCTAG|AGC	AGAAAAGCACTTGCTGAAACACAAAGTTTTGTT[CTGTCCTCAACG]AACTGTCTAG	u12
< -0.9008	GT-AG	GAT|GTATCCTTCC...CCATCCTCAAAT/TGGAGATTCAGT...GCCAG|AAA	GGGTTGATTTGGAGATTCAGTGTGTGACCT[CCATCCTCAAAT]TTTCTATTGCCAG	u12
< -0.9219	GT-AG	GAT|GTATCTTTTA...TTTCCATTAACA/TTTCCATTAACA...CCCAG|ATA	GTTGTGAGGATGAAGAGAAAAATCCCGGAGTTT[TTTCCATTAACA]ATTCTCCCAG	u12
15,18d6
< -1.1178	GT-AG	CTA|GTATCCACTC...ATTACCTTAACC/ATTACCTTAACC...TAAAG|ATG	TATCTCACCCAGAATTCTAAGTGACATTAAC[ATTACCTTAACC]CATAAAATAAAG	u12
< -1.1759	GT-AG	AAA|GTATCCTTTG...AGTTATTTAACT/AGTTATTTAACT...CTGAG|CTT	TTGCATCTCTATCAATTAATTGTGTGACTTTGAGCA[AGTTATTTAACT]CTCTGAG	u12
< -1.1759	GT-AG	AAA|GTATCCTTTG...AGTTATTTAACT/AGTTATTTAACT...CTGAG|CTT	TTGCATCTCTATCAATTAATTGTGTGACTTTGAGCA[AGTTATTTAACT]CTCTGAG	u12
< -1.2492	GT-AG	TTC|GTATCCTTGC...GCTTCCTGAAAC/TGCTTCCTGAAA...TTCAG|GCC	AGTCAGTAAACCAAGCATAATAAGGTGAAGTCTT[GCTTCCTGAAAC]ATATTTCAG	u12
20d7
< -1.3807	GT-AG	AAT|GTATCCTTAA...GCTTCCTTCACA/GCTTCCTTCACA...GAAAG|TTG	ATCTCCTTCCTGTATTACAAGATATATAAT[GCTTCCTTCACA]CTTCAAATGAAAG	u12
26,31d12

# example of a U12 intron that was only discovered with the bed input
grep CTTTATATGATAATAAGAACTTTGTCCACAGAAG gff.meta.iic bed.meta.iic 
bed.meta.iic:ENST00000706955.1_intron1	-0.1333	GT-AG	CCT|GTATCCATTT...ATATCCCTAATA/ATATCCCTAATA...AAAAG|GTT	CTTTATATGATAATAAGAACTTTGTCCACAGAAG[ATATCCCTAATA]ACAAAAAAG	9301	.	.	.	0	.	.	u12	.

# but the intron is in both intron.iic files
grep CTTTATATGATAATAAGAACTTTGTCCACAGAAG gff.introns.iic  | grep ENST00000706955 | grep intron_1 > out.gff
grep CTTTATATGATAATAAGAACTTTGTCCACAGAAG bed.introns.iic | grep ENST00000706955| grep intron1> out.bed

# the number of u2 introns also differs
grep u2 bed.meta.iic -c
401325
grep u2 gff.meta.iic -c
229855
```

Just fyi (could be posted at the main page if you like), I did some runtime tests with a large set of 519938 introns
```
1 core
        Elapsed (wall clock) time (h:mm:ss or m:ss): 18:29.39
        Maximum resident set size (kbytes): 6491676
2 cores
	Elapsed (wall clock) time (h:mm:ss or m:ss): 11:11.14
	Maximum resident set size (kbytes): 6052796
4 cores
	Elapsed (wall clock) time (h:mm:ss or m:ss): 7:38.78
        Maximum resident set size (kbytes): 5778872
8 cores
        Elapsed (wall clock) time (h:mm:ss or m:ss): 6:17.90
        Maximum resident set size (kbytes): 5658400
16 cores
        Elapsed (wall clock) time (h:mm:ss or m:ss): 5:50.76
        Maximum resident set size (kbytes): 5556492
32 cores
        Elapsed (wall clock) time (h:mm:ss or m:ss): 5:54.85
        Maximum resident set size (kbytes): 5489020
```

**Comment by MichaelHiller** [comment]
Hi Graham, 

thanks so much for quickly fixing this. It works now and I can run intronIC on essentially all introns annotated by RefSeq_all + GenCode. I also understand all output files now. 

I also ran a large test feeding either the genCode gff file into intronIC or converting the gff into bed6 introns. The output is identical. All works now. 

Just fyi (could be posted at the main page if you like), I did some runtime tests with a large set of 519938 introns
```
1 core
        Elapsed (wall clock) time (h:mm:ss or m:ss): 18:29.39
        Maximum resident set size (kbytes): 6491676
2 cores
	Elapsed (wall clock) time (h:mm:ss or m:ss): 11:11.14
	Maximum resident set size (kbytes): 6052796
4 cores
	Elapsed (wall clock) time (h:mm:ss or m:ss): 7:38.78
        Maximum resident set size (kbytes): 5778872
8 cores
        Elapsed (wall clock) time (h:mm:ss or m:ss): 6:17.90
        Maximum resident set size (kbytes): 5658400
16 cores
        Elapsed (wall clock) time (h:mm:ss or m:ss): 5:50.76
        Maximum resident set size (kbytes): 5556492
32 cores
        Elapsed (wall clock) time (h:mm:ss or m:ss): 5:54.85
        Maximum resident set size (kbytes): 5489020
```

Thx a bunch
Michael
